from typing import Optional, Protocol
from uuid import UUID

from app.modules.providers.infrastructure.models import Provider


class ProviderRepository(Protocol):
    async def find_id_by_slug(self, slug: str) -> Optional[UUID]: ...

    async def get_by_id(self, provider_id: UUID) -> Optional[Provider]: ...

    async def get_by_user_id(self, user_id: UUID) -> Optional[Provider]: ...

    async def get_by_slug(self, slug: str) -> Optional[Provider]: ...

    async def add(self, provider: Provider) -> None: ...
