"""create unique key to customer phone

Revision ID: 86049b9c6690
Revises: 79586761cbaf
Create Date: 2026-06-05 12:58:32.973219

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86049b9c6690"
down_revision: str | Sequence[str] | None = "79586761cbaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_customers_phone", "customers", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_customers_phone", "customers", type_="unique")
    # ### end Alembic commands ###
