from typing import Protocol


class UnitOfWork(Protocol):
    async def flush(self) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    async def refresh(self, entity: object) -> None: ...
